# GameMode — optimización automática al lanzar juegos (system-wide).
# Se activa solo durante el juego y se revierte al cerrarlo.
[general]
renice=10
desiredgov=performance
softrealtime=auto
ioprio=0
inhibit_screensaver=1

[gpu]
apply_gpu_optimisations=accept-responsibility
gpu_device=0

[custom]
start=notify-send "GameMode" "Optimización de juego activada"
end=notify-send "GameMode" "Optimización de juego desactivada"
